repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-merge-conflict
  - id: trailing-whitespace
    exclude: .*\.mustache$
  - id: end-of-file-fixer
    exclude: (.*\.mustache|samples/[^/]+/src/main/java/swagger.json)$
  - id: pretty-format-json
    args: [--autofix, --indent, '4']
    exclude: ^samples/[^/]+/src/main/java/swagger.json$
  - id: check-yaml
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v1.5.0
  hooks:
  - id: pretty-format-java
    args: [--autofix]
  - id: pretty-format-kotlin
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
    exclude: ^config/detekt/detekt\.yml$
- repo: https://github.com/Yelp/detect-secrets
  rev: v0.13.0
  hooks:
  - id: detect-secrets
    args: [--baseline, .secrets.baseline]
